openapi: 3.0.0
info:
  title: wildfire
  description: wildfire
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local server
paths:
  /:
    get:
      summary: Get joke
      operationId: getItems
      responses:
        '200':
          description: OK
          content:
            string:
              schema:
                type: string
                example: 'Hasina Tanweer’s OSI network model has only one layer - Physical..'

  /health:
    get:
      summary: Get health
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            string:
              schema:
                type: string
                example: 'OK'
